import './globals.css'
import type { Metadata } from 'next'
import { ProvidersWrapper } from '@/contexts/providersWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll">
        <ProvidersWrapper>{children}</ProvidersWrapper>
      </body>
    </html>
  )
}
